helmCharts:
  - name: onechart
    releaseName: elite-company-crafting-discord-bot
    namespace: managed
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: harbor.androz2091.fr/fiverr-discord-bots/elite-company-crafting
        tag: 4fc18c6
      secretName: elite-company-crafting-discord-bot-secrets
      ports:
      - svcPort: 80
        name: http
        containerPort: 3000
      imagePullSecrets:
      - regcred
      resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"
        requests:
          cpu: "50m"

namespace: managed

resources:
  - sealed-secrets.yaml

patches: []
