---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: airtrail-secrets
  namespace: home
spec:
  encryptedData:
    DB_URL: AgCoTztTMT8Ets+MjfJx8AL82LB9wvP+9GsZ/WxhNJkqSsUoAS+8RI18ySDGX13L3O8L49gXUWqEPt4sK44GPCd0kip17EhM5y6ysNZN4SGac3xgMp5XaKcKYzR4zvz9+IVG0zSRjnh6EnXdBfaRBHh19eke0younZT6s+efK/psYLIPBrU4+6SIjo9fiYDq8xbZbUjgavyTpV4FutlRl3IVqieuQ3y3QC+s+9ntovLNrgUruf3h3VSxtErCXcghavD84U+YDk07kIzXFLD6FNI153FfYnxxF+ILRIqMWgJGuVuWASg1eN7Ra8lxMemLnko/yN+rFC1ghnV/jgjkjd3C1KK3Eh90Kzjd3CadGmoo7EiLrXH/+xnIIishOAiSz33AgrNMCq4wnsStF+uVLViD9GH8qoI5YWl3lZHMqUiYXPwq97e3bU9pXA56KUkKe/HqIsJX34C8OY8gacYZelxTErD2+nftP00/EQfHIZFWskxjDyMKic2Lmkj5PTOixp/BN7XFWzJQm8eO7C/LOD4qyxSwUqpvSYbOh7M5ZmxQlVmz1RIX/ZuyYAYFN8ESbVS+qON4RRBm38CYHD+QCMVWO7sYzoM2yzL155qgIVeNm/s29qsZri0qpHp6AabbfToPdZcIN5kK0PLrTg6FoWGTbfyGRH2sZWqsjXYO7dOedEoC64qkvo8gtnIfDC37V8dC1rLgLWgd/kgHa9wFyMcM9HzpmB+E9ZREwMSzEnae0SzmZU2/LpycmamqzIyxB+7zHAXP1h9uN/PLpIdIcqmeHjy/ZLtJnSBlMH0aeE8UgPJGQqKM+CCD8dr6E9qNkgprSA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: airtrail
      name: airtrail-secrets
      namespace: home
    type: Opaque
