apiVersion: v1
kind: Pod
metadata:
  name: backup-paperless-mnt-media-pod
  namespace: home
spec:
  containers:
  - name: debug
    image: busybox:latest
    command:
      - sleep
      - "infinity"
    volumeMounts:
    - name: paperless-media
      mountPath: /mnt/media
  volumes:
  - name: paperless-media
    persistentVolumeClaim:
      claimName: paperless-media
