apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: home
  labels:
    app: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - name: webserver
          image: ghcr.io/paperless-ngx/paperless-ngx:2.14.7
          imagePullPolicy: IfNotPresent
          env:
            - name: USERMAP_UID
              value: "1000"
            - name: USERMAP_GID
              value: "1000"
            - name: PAPERLESS_CONSUMPTION_DIR
              value: "/consume"
            - name: "PAPERLESS_URL"
              value: "https://documents.androz2091.fr"
            - name: PAPERLESS_TIME_ZONE
              value: "EST"
          envFrom:
            - secretRef:
                name: paperless-secrets
          volumeMounts:
            - name: paperless-data
              mountPath: /usr/src/paperless/data
            - name: paperless-media
              mountPath: /usr/src/paperless/media
            - name: paperless-io
              mountPath: /consume
            - name: paperless-io
              mountPath: /export
              subPath: export
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: paperless-media
          persistentVolumeClaim:
            claimName: paperless-media
        - name: paperless-io
          persistentVolumeClaim:
            claimName: paperless-io
