---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: paperless-secrets
  namespace: home
spec:
  encryptedData:
    PAPERLESS_PASSPHRASE: AgBrXdO93k23Y9vSGlN7ZSwUnwgB/bumy8stHB7gNtBO78AbXGWmGUDjjG8IVR7NDMgGMsWL7+cZkGURaxyc5iAAzrZ+6R7uMq2pNsKeIB+hWbPTUeZtyY/2hiGgh4YUpOOkcc7/hpzNFLaz7jqHj3UdG1elEBReapNnda5HZJiMMKDtcwxtUwqmy0Q+TeNIupLPPDkW++kJmKVJDY85WPiJgR8NXQdAKKJJBTuQ0DSzKKQGXcTjmwsmNpZ38AN77mRvN5rKf2We0Gda7cnfv4BVgXX2SfswajfXEomBC5U0cLWR5OkcQDGa0z6Fdp9XbUr4GrtpqldDuKurcc+OCLuwzO97eDGqJO1GhYo6DqY3O4uoLYxSEOJ+dgF6sJ1Ge9DjqJwSGRCLzqJOEM9t7l5LLVID8Lp8CRtoygCeNm1yip6eI2hnkJMBsQ1N6n/sq6X7H1zY6kSYjbHXGKIqlFdPgc/r4s/KxqXzRAqRhxCFW98+Lkb5rKzlPUCRrRkLp+GucUsGGJeQj0muveIo4q5apVR3zujCK7eBb5VnrIbcZD6GucbYrLzQ7gBwihLOAFSDk+edcTqVIkvnfxloUHe4SPjEh0lI8porLlCV3jEA+6+rtVy+3DXFhL52b3pAXPJDgZVKiqCCsNctPEH1zGGCI245i2BpSStDAOf7wU/XGqHeYxo+ncj7cGjCU3dHwEl8OAqLRq+if+ob5QlZiA==
    PAPERLESS_SECRET_KEY: AgA3Op6PxVQUpz+9AVBx+8o5BqAks09GOrnZ2t3FqGtxd0g94QDGUlktmM8BYQ/nqAHqNVGGJLQOVY2//lZp1lG2SCPMTZhW3AnrZro57NILOPwWx+kmZVSyUJYQKpBYOanQOg0BSjwBDl6pQ1+YVKH5VoWWBt0Bf7R3OBLlBXG5pB2mSlBjodtPuSWQ47YFSuPPg8/IXQhA3rQKg5d4AOpaxdWY5AZbxVtkdbBpaEQBPaY3aAin2Wyg483+100SqLwg2ERI4OdzInpJPPF9X4jmZeaPBlH4FS/SgeEu62esebbZFAIwUnG9USQ2gZ3+IIBM3McFsg4ZRAGmFRwEplSt6gMYfxYv3JnW2cJokgLnolpZd6R1lnMMtBNCkowBj7rEYatP7FNF1/P4he8XEo7ibsrXHTCiEPnvpQNL/1ah2K9hXahGjHc99HnppS3wvWBFbTHAaznICAJIvzDOp5TPrFn03atcGC7PzXWreXiYvwNTW3rjRfwwtbNIYNIHXJYy1rhTQb/jUct3TXsnSdUXWXMOwiQIxKAaUEydVBEQH4xy4bZrhOXbv72VP3aW3eG1+twMulTgIEHU8ydNFWXyQbDQb8n1r8l5cWcf+vcaPMZ4WRkD4ipH9IDJlMIL+m2AY/LRb7bdEe2CKq34PjIB6z++HYLnxNWibcyy0o1IDKTne9LHgHzXccHA4OK5AFNtRj6ufbMCLOAiEbVmj841Qgg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: paperless-secrets
      namespace: home
    type: Opaque
