apiVersion: v1
kind: Service
metadata:
  name: paperless
  labels:
    app: paperless
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: paperless
  type: ClusterIP
