apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
