apiVersion: v1
kind: Service
metadata:
  name: overseerr
  labels:
    app: overseerr
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: overseerr
  type: ClusterIP
