---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql-secrets
  namespace: db
spec:
  encryptedData:
    postgres-password: AgBL6k7d5h6Ur0+KxpkAmT+Xcwn4WP+N9s4D7ELMArGEpWUVfUYbmm4LWUBLTdhRALo3hhxf/tYtYQcv56ZqMSCcz9rsxfmq+mb56wTPpOPqAJAVJ2PfO0WBIz1UriCRggv87B8Lb9DGSpajaHy3fe3kF9r4SkCIA/0fWPuo+WXJnxzzUps0ovEAyTgoEJxXS/VNbQFvn8h2VqqD3BIPt8QUrNBdzmftPhf45vEUmX1og7t5Kb8H4lJ4FvsyK0djQvPC/EgSo7lXl5tWL2CDo3EQhnpz+s3GX13+xpFU/zDvuvfS6cfutlRqdHzECMOZYQylKk17vRbkAvAK/y7MqvQzqB9RAmptk2mto8jPF8oTjW0KatRj1xKVjyAOfozYem6xSj1crNBTZBYxDVnAa1Pzg9oS++4fwMzCTyZzp0ErTAvqds/PoeRhMfTTi5nGNmhwdQxlD61fyW8MfnHn4PtNbMLPe992jQqMe1UqWIYBLz034FQ9OVNonmJmE0VTQfkdHMpkb0nTEa8NtkKGZ9iAVLSeBqPyA7hWSbyu2uoDb6eFRIh6XgqwfO9uk78uZyaB1OVawej1ieYXyh2K8Jr9nyiJJYuAn8Li4o0G2o3AUTyAR5jwUeuc2T5mfPHs1suZjFN3j0VF9XwktfALxa8Q3Q3auufnwNPKVlFn16WNuxtSk8MiRCyR66bHSuB5L6B4txrUUQbID1KrjiM5XriOXq43wqIcgc4V45CXuO+DZhTNl0sd21lR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql-secrets
      namespace: db
    type: Opaque
