---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgCLiPq1TcfrkD3oGJmf++WtLMwL/lY2Ixyjtt1Mwit5SkPjdNG7Tocr6znbaDmIcB0sAbEtLGzwPIHfbTYwWMF61IVjX1agyEnfc1dLZaoyfFvKKp5Dk5jmcPfyJvsr4y8D8g42aP+DXtrcnGIhnyP1U/xWGhYvmgZRfGMTDSx2awf5ae7yQEuznUObBMnXoQIxdhHlLX7oeKYD7rtbjejtRLZW89vIQaHdZqxsEmRw8fvkBrEZ+Ms3G5XXDDwoiynCS6ImtN4HInFMh/FlHVIeXIUScGLvx3DWe/T8FVOYoLyNTTuR+23e7YSc6NiaG92EID4m6ydp9W++G3qozQXAQ+O7hzcNB7FjCGLRu1QH9dx4IURQXg0wo66MVzPHNYhf0F1JcgmfHuCxiAjJAvx7WZJMgp7BzaOR4GPfAxKsv7lbSY5Js4CDAEo9t7U35jOxUBY7ZH8X4bxU2dCIgFCdgaKumfysP6W6BG50S/06RHCDXzn9KbBTJYhk3sIscxxeS96o34Ikpm92dzgxmZA1cwHlbDYpkedb6xjIdQ/sXOVVxAFBSGG2/DS7GFac2nijcF22EXoSEzLJdLAn7X/Mba59s9NiIFzqufLfVJnv95b5LgCpnRTFhs8rUhCCvYVOpsiLvRNOFhoGCeaCsgP0hNSE/c00buOAlFwZKERjBwDnUIGsmYgxBkNinXS5YFT0lC3jc5heNRmCkyfDMe+dFm5yyHe3TWgAw5W2gprcruOhk3H5w2NAZEUK9NZk9uYZkjJMaDKiSEQAtl3PRvvjNwkBoHCgdX4HXIgKtqg0qcWmy9DlJEF67yqpLQ8bIfu6GhBzjB6jsVXSfHQTZ5uEhx4UqZ8JF5xJcL5S4YpQUNvJBM83na7im4Nxh1yflFLNZh4NOIYhZg0/3ysm67fppUqY+V7ugk6J3m4BWD3KS+e11jvYDP4g2VQkNj2R+yEy/V8JG8+WS9udFYEPxUQvrbdasZVumxaFq/D7ymX2yxXkG8FJA/UP9xS7O0avAlnNKtvorrfkgSfR/RFEYjwR0fgoYKpaBSvcwxnNVEfFeq4IN+b8w3zN4Cyg3UAcsbD91hJ7b5JuwOETZcqJbMvMTjLtf45NopFQPZsKPgShR6P+M+a/pxPScO2Vd1q8geLhDVV0eiR5XPcDms/GHuym7qIPA3zsBnTrx228a56mJclo8hqwZK9CqVB/wvcX2yjDDgHFGWqmx5QRYCb7Zrnaf+L7XXauokegwwsGfxXbNinsQMS6jO9jCI4Jb4+8GPNMzl8dQpDXMaot2ogaf4KWLTOsRSshcf+t83RZ6BmVcdKJFkXbCbDev2EiCkO57ngkx350B/K+mrZz/S9W
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: timetagger-secrets
      namespace: home
    type: Opaque
