---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgAmqdULSDclYmnQUgeutQ3/5Vzqspfkkmo+x6MGZMRXw0JC+Qu6UcNrs1JamnoeHLdahaVKcbuEHPkmCD1AzljVOqsDQANBpUmTw0F3bL5Til/C+83SSWbE6H2dZSUwU0XV/atvf9OwLLPatG0UFVjR6LVeTeVSPFpfKJKr6LG6xbxeeOi+IMkQdEVZVYuUxJiWDJu4mMbuTvmw4zFXEhFpct51GfSLJpjC1Q0GXnOqCekgE4/N02qh517CN8aY5L/GMM90N3Hy7JrvClk97u5CZLr2QolUMQ/pMonYPc+ZXfVufYj59QHj13NPQnQisjWLbUdgRGRwET1BeaNmsJwsMMbjawAJh6aTjKZ7wCdIaBaCb7cSWUehUoRMKHTjM2oS8CBubdfumUoqfruFS9NdZH2iefJ83js/xCePRezANSB+Hb7pFpoU5MQHv+I+1oRg2Z1MzXBVsO8q0tIKdfE81OKi/Cm1nOD0cIvPYBoJmFzhOcVLtATi6Fdl8i7CKIQDklLxQlgPPdpKEe95SH5Gj74j+DqdwApktLMw0f5uyEJvLF/oXr8rEl3n8lqQ6Aos72Wlc6pjwSlHRZlm5V1/L3ajV+5piA50MLpEkR6chf6Salpu/LMri6y+GTfhhaqPFTZZP3kYuumAX6XrFID4bnCuV+us/nBjBi+mFJAMR0LelOdCdjRPe3ZXL9oxX24fzUeeXjAug33xA/Ec/RQxx8oy+eBpxelXO6CFOlFJlHg3H1wzhDDngt/uMn//ucm+Aybgd39Yf16cdNkWVBTk4Oa7yvtYOOzWH7fYwMMS0VGMkrAEW8meajuy9kTv+3vNWSnJHRJlZ8INeVc7lNa/AEbmM2kGZf6yjPlswpBm9lyj+J3COXgcolvHLCDThh9oSxYocoqu15z/K1zFtxwTzFDDZzA+d07BY+nG+LTdnM70Eruv/+6a4zNF+HtTf8HKBIrGydDbz2YT+MF9ibfER4gD0RXdkzRSAU8AhIOZHs+Lh1Sl9CIX/g4fTi52i60+UwA2kNVeaH2M+2LEEK9S0WweRSB7s5pW/OJO8gZhn0Dfl7HlE48OykXsjXvJl9QRNa6UirdwLEJBFp2y3w5zifw8T+oMuRJAK0vFAMvS9SKiPpuy0usF1Lx0GYS4Edx2kgc8msrkQe0eFs9oOjkffGG/HYA5nNSLt/k3kQj0TVgnmTH5N9vAkSON8cKOiXp5rSy/+civKTaRnzpQjDE+eN4nz7WiYwDb3IobUPsrBiKAupYiWvB1pey82yR3Y5x4jUHF6SzO0Ckzl6Q6maUxlw9EnBxggeXgqr0wu9Qapm44tPfi3QGsD5m6rP8dcDQ9n6Kvav7rV4hHleEpQfwTgQD9IiTvwpmb0g1hSPM/197zZ5QMgZYczuVrj1ERfo7AQtRk64WhiUfga9yaSVBtI39KAlUraq9su1co
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: timetagger-secrets
      namespace: home
    type: Opaque
