---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgCm2IGwyiweneQwaxSfWpeFy/uELNMN097PSDGmoBlswqZXLk8Cl5/CAsqCqk0TFZF6V2GLYK8CaEm3jQ/DX5zi5ZNJa9F5eWkY83NITwYu/2JqbQwD6QRO4kCieghk+s4Zp/dX0XUwfoms9DnFdn6xBF/pCFBIQW27GsmVpb3AHzVdzE/cH+rygRuWmcmNPo7jjJ0/cHUVPKHo3LtpXmndppEhc/9e/kksQh9af8RI7JT3wNgPJUvgLOknoX2MjPsTwSW6qle7IjWm9yGC6ft1RW42XthzE8ZNrdh2mW850Za+naEq1QXztOTePTEX2k3J32BpoYavXd8fhkmwwXHi5/y97tsi5aWv0AWWl2yry8ORMWhuy0/qukiWa5e2ALxQFDr3d2ue8yZpFJxl4cF/w7lBkwwDfCeP219bPGTDNq9rOV7qEaYerGsKJjvyns+5Kv57cLpiLIkQXFbYcHvW4XltU5Yly35ao5QMgve726XKsGumYk9/lY0MN3Y2jbXjx9RIWrMMhcgBytw4waa4lUOTMG3MqAMX3jbdDR/VCGv/yhiv7E0+k1svFnovtTg5vMTs6qNFlYs4gpjEOKEFhuHQnMuObRPXTyJUY2D2NEt6hxU93ZFRJuYzF/tT2/0IKfmLSvBP8fS9BFN9Du58BbdioZY52iPIFXFTYUUCHun916jfE2MlKjT49A8AxTLkn6Gk21s6kXNnm7qyXscdL7JL7rfzddS24WhlkBf9z9xoWHrcEXrL0HbuBiy/g13yz6HU66BSzVpqChyvkGZpVf8AfeJVBODiCQCwuBJKJgYTR1sVy/j5Z5USg9ncs+IXbWk+6HlAfstV3GsngPmPZA1sGRyj/uRoq0oGQm5RvobDIuuljybS52nJvbPcp40BTck0nVHIHTPjNUWrCKh8lcX8OeUS2YRwBe0e3Qb4PtRUd+XOu4W3T5+5Gf7HscmVfZKjp6s1cNbQUnqFUv7oBTHGpym5WMFedrYqr/fviR+zD4fgVjY5EqtciJGst5pd//a+KYD0zs8jedWY8nXzs17uMT1swX+CXMcjrpsm
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: timetagger-secrets
      namespace: home
    type: Opaque
