---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: timetagger-secrets
  namespace: home
spec:
  encryptedData:
    TIMETAGGER_CREDENTIALS: AgCfWEslYX8/cw0tgfa0ghfaKhPQEOvsmCSRl8+oL/kSbPhMalnAc9SIq3g8rHqo+dJFtoKj/8qTnbQ/5Q1fnUqBA6OegQYBKAYVLjrBAuIBE/qt7sJGBAzR9rQ4o6S9ANvlHhuF2BSo2IkCGyLcjaryjj38DsYU8L+t1/PkPzmR1Q7GWT3/XDHdJ6art5UOa4OuE90VSxmI/LxDnc6kqQJZg4Z6aDQ1yKv+mD3EmYnWfR7chYDoyCqbTDIu/T4nndDTfDY7wG7u71tH3Rp+cKrUU+wxciyOxvAiLAGCFpbpIzC+RnJUyjamTHK9tqFj5+HoGKY8HOWAb+j3D+ZPldCA1dhGAWm0HNtc9DqyAfRSATHtUj8n+TRGXLKpLI7OM8jb4b6AI8zTCGKmPifTVLywZwqEAihqVq/A1hRQ0hr5xvTTB6pJ4k0r5kRuB2DKFhn7iJe4zwVRIEq0UffkWtX2fW0IAEftYlNAsDFMXhrqQ/zFLbJiG4nAHQhVKfCVOnc1kf0EaN/CG8zBrdqfXZ3EjVICDpUiODW90FGZTTOCbVyBsm7x9ptvcg4hSBD3oghvQBkLXFoxK7dRLmnqxR881BzYByvHV2XSS1aiF82cKx2heKAToYaYV7nw89pl9fDKC6/p775eb6bR06z8QFyCrd/K1Tu/96h6zu4H1sFOWW2hOMgXCyBggB/WasJvId/bTuOgSiin7S7M+bYknicp3+TSxJ/KBTsIADG55H+TfnsumgWm4AxmhvJiEcoH6UC5LQAmddeJCtB+rP+bqzcHVih9KrUPc3U7l9KcKT16+3ILKvc+deb/oaL4IjrGr0mv00VZqld4Isq2nWt/0zEf619RcX7OEuli0emnI1Z9XNHq2O9FUKJg3jvy8OW0wdZcZthUrRnJTESUVlgdatdOYOMSvipZZUMynlG1tLh398GUMWnbD0W/RLZt2wGTGl4qXKXYBpSaw57Qqn398TwscILeGFr/Czy2d3wwgDxHkArRnULHLUILrpIfVdcED/1Y0D+GPC6ITJTja6SwYr0pmvUjL94WOwcSJboy4X4NQEZ/0H3vxLTBcueauXzytDRyxXtgboP9YS1tvIumyv5UCw0Nckn/TXg0T109GyzgB5RLrX9upjtOiFmCh7DI++4X8j3lxQI7gu3T/QKx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: timetagger-secrets
      namespace: home
    type: Opaque
