apiVersion: v1
kind: Pod
metadata:
  name: backup-immich-mnt-lib-pod
  namespace: home
spec:
  containers:
  - name: debug
    image: busybox:latest
    command:
      - sleep
      - "infinity"
    volumeMounts:
    - name: immich-library
      mountPath: /mnt/library
  volumes:
  - name: immich-library
    persistentVolumeClaim:
      claimName: immich-library-pvc
