helmCharts:
  - name: immich
    releaseName: immich
    namespace: home
    version: 0.9.0
    repo: https://immich-app.github.io/immich-charts
    valuesInline:
      useDeprecatedPostgresChart: true
      image:
        tag: v1.137.0
      immich:
        persistence:
          library:
            existingClaim: immich-library-pvc
      redis:
        enabled: true
        architecture: standalone
        auth:
          enabled: false

      postgresql:
        enabled: true
        image:
          registry: ghcr.io
          repository: immich-app/postgres
          tag: 14-vectorchord0.3.0-pgvectors0.2.0
        global:
          postgresql:
            auth:
              username: immich
              database: immich
              password: immich
        primary:
          resourcesPreset: large
          containerSecurityContext:
            readOnlyRootFilesystem: false
          initdb:
            scripts:
              create-extensions.sql: |
                CREATE EXTENSION cube;
                CREATE EXTENSION earthdistance;
                CREATE EXTENSION vectors;

      env:
        DB_HOSTNAME: immich-postgresql.home.svc.cluster.local
        REDIS_HOSTNAME: immich-redis-master.home.svc.cluster.local

namespace: home

resources:
  - pvc.yaml

patches: []
