apiVersion: v1
kind: ConfigMap
metadata:
  name: invoiceninja-nginx-config
  namespace: pro
data:
  default.conf: |
    server {
      listen 80;
      server_name ninja.androz2091.fr;
      root /var/www/app/public;
      index index.php index.html index.htm;
      client_max_body_size 20M;

      real_ip_header X-Forwarded-For;
      set_real_ip_from 0.0.0.0/0;

      gzip on;
      gzip_types application/javascript application/x-javascript text/javascript text/plain application/xml application/json;
      gzip_proxied no-cache no-store private expired auth;
      gzip_min_length 1000;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
          fastcgi_pass 127.0.0.1:9000;
          
          fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
          fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for;
          fastcgi_param HTTPS $https if_not_empty;
      }

      location ~ /\.ht {
          deny all;
      }
    }

