apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceninja
  namespace: pro
  labels:
    app: invoiceninja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoiceninja
  template:
    metadata:
      labels:
        app: invoiceninja
    spec:
      initContainers:
        - name: fix-permissions
          image: invoiceninja/invoiceninja:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              chown -R 1500:1500 /var/www/app
              chown -R 1500:1500 /var/www/app/public /var/www/app/storage
              find /var/www/app -type d -exec chmod 755 {} \;
          volumeMounts:
            - name: invoiceninja-public
              mountPath: /var/www/app/public
            - name: invoiceninja-storage
              mountPath: /var/www/app/storage
          securityContext:
            runAsUser: 0
      containers:
        - name: invoiceninja
          image: invoiceninja/invoiceninja:latest
          imagePullPolicy: IfNotPresent
          # command: ["/bin/sh"]
          # args: ["-c", "sleep 999999"]
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "0"
            - name: REQUIRE_HTTPS
              value: "false"
            - name: TRUSTED_PROXIES
              value: "*"
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: APP_URL
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: APP_KEY
            - name: APP_CIPHER
              value: "AES-256-CBC"
            - name: DB_TYPE
              value: "mysql"
            - name: DB_STRICT
              value: "false"
            - name: DB_HOST
              value: "invoiceninja-mysql"
            - name: DB_DATABASE
              value: "ninja"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: DB_PASSWORD
            - name: QUEUE_CONNECTION
              value: "database"

          ports:
            - containerPort: 9000
              name: fpm
              protocol: TCP

          volumeMounts:
            - name: invoiceninja-public
              mountPath: /var/www/app/public
            - name: invoiceninja-storage
              mountPath: /var/www/app/storage

          resources: {}

        - name: scheduler
          image: invoiceninja/invoiceninja:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                php /var/www/app/artisan schedule:run --verbose --no-interaction
                sleep 60
              done
          
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "0"
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: APP_URL
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: APP_KEY
            - name: APP_CIPHER
              value: "AES-256-CBC"
            - name: DB_TYPE
              value: "mysql"
            - name: DB_STRICT
              value: "false"
            - name: DB_HOST
              value: "invoiceninja-mysql"
            - name: DB_DATABASE
              value: "ninja"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: DB_PASSWORD
            - name: QUEUE_CONNECTION
              value: "database"

          volumeMounts:
            - name: invoiceninja-public
              mountPath: /var/www/app/public
            - name: invoiceninja-storage
              mountPath: /var/www/app/storage

          resources: {}

        - name: queue-worker
          image: invoiceninja/invoiceninja:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              php /var/www/app/artisan queue:work --sleep=3 --tries=3 --max-time=3600
          
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "0"
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: APP_URL
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: APP_KEY
            - name: APP_CIPHER
              value: "AES-256-CBC"
            - name: DB_TYPE
              value: "mysql"
            - name: DB_STRICT
              value: "false"
            - name: DB_HOST
              value: "invoiceninja-mysql"
            - name: DB_DATABASE
              value: "ninja"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: invoiceninja-secrets
                  key: DB_PASSWORD
            - name: QUEUE_CONNECTION
              value: "database"

          volumeMounts:
            - name: invoiceninja-public
              mountPath: /var/www/app/public
            - name: invoiceninja-storage
              mountPath: /var/www/app/storage

          resources: {}

        - name: nginx
          image: nginx:1.25-alpine
          imagePullPolicy: IfNotPresent
          
          ports:
            - containerPort: 80
              name: http
              protocol: TCP

          volumeMounts:
            - name: invoiceninja-public
              mountPath: /var/www/app/public
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

          resources: {}

      volumes:
        - name: invoiceninja-public
          persistentVolumeClaim:
            claimName: invoiceninja-public-pvc
        - name: invoiceninja-storage
          persistentVolumeClaim:
            claimName: invoiceninja-storage-pvc
        - name: nginx-config
          configMap:
            name: invoiceninja-nginx-config
