apiVersion: v1
kind: Service
metadata:
  name: invoiceninja
  namespace: pro
  labels:
    app: invoiceninja
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: invoiceninja
  type: ClusterIP
