---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: pdfding-secrets
  namespace: home
spec:
  encryptedData:
    SECRET_KEY: AgCuOlUEMDWpP/jC+qi9AzbnLgC27GZovxp4JxnY13+Qy1+FY8tPpQqfnFPQGXZbVaNq8YimDOFyBR6qILXDvfYChm3IhkxnWwyVWitbmwdXPJ6zcB8BKD83vTaArNjWP7OLnwI81IxPS9pcqNWt2FZEee3gaRNL61m8wb5qsGJbIEY2PWRJVMyV39SP8Ywn9VyTiP2NKsMHG001R4E45eoZ3eY9ivx3oNWBr10ewfIA3O5eU42LzJAb9FOLhtW+aw6ejUhS7K2c61EE88jTRarChxb4k4Fsfv+V7d6z4t/EaUMsXMH+0lm7bh90kN9ve4SrdNBcc6EBBX0ftNfL/6rdOeQY73T0SF7kLAYDJoIRfQU5sgCtFLUSW9B3GCfPG5Ta/rdt5IuJmzJSTdWr87aCgOSSo2Eo5GvZsULI0p0vdrHkbuzfzRtpSWjb1nEpwYd0tx/8/onhIytP6LVaHNv/NlphscF9MsZnkSqZQxBh7d0NnXgen9F9XJq8E4icSxwls+TDGgg0iO/py0rn/Cf75gdjBP+/IkiXwv1oJzMTLqperdc6hELXQHj7rbXGWJMcLBxlHFYXY1uvM90a05T8Q0vI+5o4r5zM90YkBQCWGBqc8+pYH5jFUgeHdkp/GOx38TtW84uoVyqz3IwStyC4GP52BwcEWOhJIppILm+6jOjTBV8Lt880gdO+PeNYSaRg41Y8Z5F4havxW7Imwb+FZ4qxbkp9nYgX+Dhk7LfWOg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: pdfding-secrets
      namespace: home
    type: Opaque
