helmCharts:
  - name: umami
    releaseName: umami-analytics
    namespace: pro
    version: 4.7.12
    repo: https://christianhuth.github.io/helm-charts
    valuesInline:
      postgresql:
        enabled: false
      database:
        existingSecret: umami-analytics-secrets
        databaseUrlKey: DATABASE_URL

namespace: pro

resources:
  - sealed-secrets.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: umami-analytics
      namespace: pro
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe
