---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: umami-analytics-secrets
  namespace: pro
spec:
  encryptedData:
    DATABASE_URL: AgCBkzQa0ePqoYa3AzpoU/RmZ3kvCpSHbtXt30xYgVLE0YnXvuupfSvwHuwBU+ibWxSoA8FKuTNav1u+M2V9FDc9mekM37MvlmHtmjXupHGH3HbqjEzjdt7NaYoC1t17O0a10ThjJ8s0oLhzPgEiDIo1PsIef+KCOBKqGtsWXgNAi3FVpuLOwQ8ClgVTeuUUNLn/ww0ieKhj3qMMCAJoUMEE6qqovaJVvGuRtlB+wOWQ8kjxdhXCotH97b1+R5hvUw+WrA5Z7TgNYUfRKGzxGz96g6Ibd61m5QcNZ578CH04wEpknzICFjYvnVFtYNqluG8LS+vMmU5ihZozy6eQUbGbUyvoiScNHL8myz1+ds3yt4St6TWDskqpjdnEwu5W98eJf5CME4pr1guIXbuaxcHrz3gsziyYQZQTwDc/d1z5A/vml0HwhpdcPly6+JzFTn1UA1Ih7NRVZ7f3qTiaoQWZSYo0mS46XAkqP9wt3kj7liHB4DqIWZhbltOdYZeTnoi1gwP4mqDACOunmstNU7efw3j2GnOoOX0k4wiPDSaLySmTH2HiZVadBVrVUg/lGwNWy2mLSMpYixStUrS8lqcC1e9hIB9yGM/mHTT+fSMF9X3GdrB8uzk3q5eEI9v/RYRq+wBGu8F+In0q8y1PrK4R5rEYbxBBLKD3nrO2ZY0auOHLCSnszZ20wNtxSTowpsiP/5G0oZD48o9ey9QBsvGASF1/Ea2AU6gvkWvw66zkTXu8sQ1Dgr6YLYDoLifb6dOg3QtT+xhiBmXoPuM0BSQpm7DJ+xxVHENu/hzZ9AxhYoXLiwCpXcDLK5m1FURGCkksWp5TLaE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: umami-analytics-secrets
      namespace: pro
    type: Opaque
