apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bonds-data
  namespace: home
  labels:
    app: bonds
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
