apiVersion: v1
kind: Service
metadata:
  name: bonds
  namespace: home
  labels:
    app: bonds
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: bonds
  type: ClusterIP
