helmCharts:
  - name: onechart
    releaseName: androzdev-discord-bot
    namespace: pro
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      secretName: androzdev-discord-bot-secrets
      image:
        repository: androz2091/androzdev-bot
        tag: sha-cdc6676
      resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"
        requests:
          cpu: "200m"
          memory: "500Mi"

namespace: pro

resources:
  - sealed-secrets.yaml

patches: []
