apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: sushiflix
  labels:
    app: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      hostname: qbittorrent
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:5.2.0
          imagePullPolicy: IfNotPresent

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
            - name: bittorrent-tcp
              containerPort: 6881
            - name: bittorrent-udp
              containerPort: 6881
              protocol: UDP

          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: http
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: http
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 2

          resources: {}

          volumeMounts:
            - name: servarr-data-v
              mountPath: /data
            - name: qbittorrent-config-v
              mountPath: /config

      volumes:
        - name: servarr-data-v
          persistentVolumeClaim:
            claimName: servarr-data-pvc
        - name: qbittorrent-config-v
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
