apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitpod-server
  namespace: pro
  labels:
    app: gitpod-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hgitpod-server
  template:
    metadata:
      labels:
        app: hgitpod-server
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /home/workspace
              chown -R 1000:1000 /home/workspace
              chmod -R 755 /home/workspace
          volumeMounts:
            - name: workspace
              mountPath: /home/workspace
          securityContext:
            runAsUser: 0

      containers:
        - name: gitpod-server
          image: gitpod/openvscode-server:1.103.1
          imagePullPolicy: IfNotPresent
          
          # Use the same entrypoint pattern as the original image
          command: ["/bin/sh", "-c"]
          args:
            - "exec ${OPENVSCODE_SERVER_ROOT}/bin/openvscode-server --host 0.0.0.0 --port 3000 --connection-token \"$CONNECTION_TOKEN\" \"$@\""

          env:
            - name: CONNECTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitpod-server-secrets
                  key: CONNECTION_TOKEN
            - name: OPENVSCODE_SERVER_ROOT
              value: "/home/.openvscode-server"
            - name: HOME
              value: "/home/workspace"
            - name: LANG
              value: "C.UTF-8"
            - name: LC_ALL
              value: "C.UTF-8"
            - name: EDITOR
              value: "code"

          ports:
            - containerPort: 3000
              name: http
              protocol: TCP

          volumeMounts:
            - name: workspace
              mountPath: /home/workspace

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000

          resources: {}
      
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: gitpod-server-workspace-pvc
