apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitpod-server-workspace-pvc
  namespace: pro
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
