apiVersion: v1
kind: Service
metadata:
  name: gitpod-server
  namespace: pro
  labels:
    app: gitpod-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: gitpod-server
  type: ClusterIP
