apiVersion: v1
kind: Pod
metadata:
  name: backup-mnt-data-pod
  namespace: home
spec:
  containers:
  - name: debug
    image: busybox:latest
    command:
      - sleep
      - "infinity"
    volumeMounts:
    - name: filebrowser-data
      mountPath: /mnt/data
  volumes:
  - name: filebrowser-data
    persistentVolumeClaim:
      claimName: filebrowser-data-pvc
