apiVersion: v1
kind: Pod
metadata:
  name: backup-filebrowser-mnt-data-pod
  namespace: home
spec:
  priorityClassName: system-cluster-critical
  containers:
  - name: debug
    image: busybox:latest
    command:
      - sleep
      - "infinity"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
    - name: filebrowser-data
      mountPath: /mnt/data
  volumes:
  - name: filebrowser-data
    persistentVolumeClaim:
      claimName: filebrowser-data-pvc
