apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: home
  labels:
    app: filebrowser
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:v2.63.3
          imagePullPolicy: IfNotPresent
          args:
            - --port=8080
            - --root=/srv
            - --database=/database/filebrowser.db

          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

          resources: {}

          volumeMounts:
            - name: filebrowser-data-v
              mountPath: /srv
            - name: filebrowser-config-v
              mountPath: /database

      volumes:
        - name: filebrowser-data-v
          persistentVolumeClaim:
            claimName: filebrowser-data-pvc
        - name: filebrowser-config-v
          persistentVolumeClaim:
            claimName: filebrowser-config-pvc
