apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailo
  namespace: pro
  labels:
    app: tailo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailo
  template:
    metadata:
      labels:
        app: tailo
    spec:
      containers:
        - name: tailo
          image: androz2091/tailo:main
          imagePullPolicy: Always
          
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: tailo-config
                  key: DATABASE_URL
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: tailo-config
                  key: NODE_ENV
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: tailo-config
                  key: NEXTAUTH_URL
            
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: tailo-secrets
                  key: NEXTAUTH_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tailo-secrets
                  key: OPENAI_API_KEY

          ports:
            - containerPort: 3000
              name: http
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

          volumeMounts:
            - name: data-volume
              mountPath: /app
              
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL

      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: tailo-data

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000