apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailo-data
  namespace: pro
  labels:
    app: tailo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn