---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: haste-server-secrets
  namespace: pro
spec:
  encryptedData:
    DATABASE_URL: AgBgc0jMXseKE/sRhbt9YhZPmG3wjIBlAnUEHAylHqlpgDA2X1KnSm32dtxf0dLota0n3zLCxrdFmp6A8iVB2IIOopZczXJr31drTs810pk6/+fiEaX5DrFM7l9mVmuX2JldxWbuTyZgi5DF5RY3/tOkq2ENkXtcYa3Pe2aLUruzIBq+eOJPfq2iTspkOhhHYpxwvI/hRkyt7yG/XyHRsDQnX4CHMxbsSZ0VLYlLeNB1NZSd7f7FsilhMZOimjpR7tQUiJravVGS5iavGPQ2eS3DHPbvaEj32HKIULc8N2i23tTT5h6HVlmSYSmIu/F3kn/1vx7NeYghfBdiJsK010/6IlTx3W7J4vHquUYmDnR8xvbEh1aa4hNCsvlMoxTOqZKAiPo2jFilcPlCNmhBWgMP+CZxAFxbZv/rhUbgQLHO5yYnHvw8aAYWnt5hj1GTqt786i906oD07jsfkdcKlXUPBluyiybVsWZHVZpycyv6lvAxPYcjwX9YIA5zWzIvABTyWPUTFwxNDbKY947jSg/9sYVWpo9qowfwMgxJVgQ/ClorQy87a2Tbe+nvJRyZ9v7KRxhoFk7nc8mGYGfRw+408nSPomWnEbk5gmJ13vXbz1KAGJtMlHlKw9giI2eoFhXMqV99N1agyna5Aey76LUA66fLm/GDnZKQmbngk09bfGC9cC/HK7MvVbtsGnGKT195OdGDD3RjOWWUpiDnG8t29vBXIfbCmSov3UI95gJh5EgIvPw9k8Uqf2t9R+PFwldVVzXhune4gmmOidljhYf4pEXr3kWlPTsovEn8u9UXFeG+WLUKvYHw08msGil8xZm134E=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: haste-server-secrets
      namespace: pro
    type: Opaque
