helmCharts:
  - name: onechart
    releaseName: clip-city-discord-bot
    namespace: managed
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: harbor.androz2091.fr/fiverr-discord-bots/clip-city-discord-bot
        tag: 419a59c0
      secretName: clip-city-discord-bot-secrets
      ports:
      - svcPort: 80
        name: http
        containerPort: 3000
      imagePullSecrets:
      - regcred
      resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"
        requests:
          cpu: "50m"

namespace: managed

resources:
  - sealed-secrets.yaml

patches: []
