[control_plane]
vps-ab240c42 ansible_host=148.113.245.134 ansible_user=debian wg_address=10.8.0.1 wg_public_key="VoqMfTab9PUETaY6GIoKFErp4aG4WrAt5apE+3KhV20="

[apps]
ns561436 ansible_host=54.39.102.76 ansible_user=root wg_address=10.8.0.2 wg_public_key="NgItXo6KRVbvktmpFRH1QCjINmaaJglLH6zJ/NlWuTE="

[all:vars]
ansible_ssh_private_key_file=~/.ssh/mbp2024
ansible_python_interpreter=/usr/bin/python3
