apiVersion: v1
kind: Service
metadata:
  name: changedetection
  labels:
    app: changedetection
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: changedetection
  type: ClusterIP
