helmCharts:
  - name: onechart
    releaseName: diswho
    namespace: pro
    version: 0.70.0
    repo: https://chart.onechart.dev
    valuesInline:
      image:
        repository: androz2091/diswho
        tag: sha-18c8c52
      secretName: diswho-secrets
      ports:
      - svcPort: 80
        name: http
        containerPort: 3050
      resources:
        limits:
          cpu: "2000m"
          memory: "2000Mi"
        requests:
          cpu: "200m"
          memory: "500Mi"

namespace: pro

resources:
  - sealed-secrets.yaml

patches: []
