apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinyauth-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
