---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth-secrets
  namespace: home
spec:
  encryptedData:
    TINYAUTH_AUTH_USERS: AgApJnTFVqo/z8DKi2A7ojBay845Eu4rHshULpiJRx6sYQhj1gM7pEM5goqKMsu4dIMrNBOGYGyIjtL/NK5UYmXw2nuzI/49DnkpYwgyFjkgpx/H1c8MC5IPqIO33oXYoGODgfHiJCkprddgYZZSnU0vHdx2ZpDtX3870kOvpSTF4ExS0bKrDHdU4lcRs7d6SXPsWbvpxY646KAm+f0+9riylyKcvCmrKUU+xRaXT3CoMdl033QS6QZCOuP1iBVwXxvEt0b2izVekzR+CjKCrNujdNczBFhKg6AmcmZc+niiC5H0lqQitkMCYNa8OAH1Mqpj3UqyEKl9wzJg5anIMXe+lHYr+0NODJiFmt0pkYRYnFpilcqv0+O+cmqceqmmtbpKgmKawV8tCBaXKQbqw/1w6G2JdiIa4COfa0rk6K0WZphDVbZOu5yWzzy/iCVrwxyBUMJTCz8LIKpTWEuH/BPhXz+PlxvOrZbD1luiFF4v6CsEtUHJwd3JcrQJEkj9BJgYk6vT81Jzcq/dmX7iXRDOxfWx4XxFKpTlTjrBHdjo8gJ6jEsV5vM/UU1Sb6XcRdSzqscZpQ2goqwNcNdyAoOlWPMYFDZPE45reS7oLQDbAPbive3OVHHKDiOgoE/l5UTzZU1MMsJe8GZAxSkh+L+/36aI++kRCzrMhLZ7fyIvptTRpNMEmzQiKxeNtbSXkqG1sfF/Lhcs2wE0iQ58Cu7b76X9UrdvCsPaouCpHPs0t74wravaAYM1OaXGtM4CqVWi/ldlj8Rq3l9/S4N4gWuCpW4=
  template:
    metadata:
      name: tinyauth-secrets
      namespace: home
    type: Opaque
