apiVersion: v1
kind: Service
metadata:
  name: tinyauth
  namespace: home
  labels:
    app: tinyauth
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: tinyauth
